python:
  # - 3.9   # build times out on python3.9 only
  - 3.10
  # - 3.11  # python requires a version >=3.9, <3.11 ( see setup.py: https://gitlab.com/ska-telescope/external/rascil-main/-/blob/1.0.0/setup.py?ref_type=tags)
